export const SIGNIN = '[User] Signin'
export const SIGNIN_SUCCESS = '[User] Signin sucess'
export const SIGNIN_FAILURE = '[User] Signin failure'
export const SIGNIN_FROM_SESSION = 'SYNC_FROM_SESSION'
export const LOGOUT = '[User] Logout'
export const ADD_USER = '[User] Adding new user'
export const ADD_USER_COMPLETED = '[User] Adding new user completed'
export const ADD_USER_CANCELED = '[User] Adding new user canceled'
